mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hxs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wx050329
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.hxs.mapper: debug
    com.hxs.client: debug

wechat:
  app-id: wxa54a4b846bc4ea80
  app-secret: 2fd98b5dee66c2732a3c30a25135bb62

hxs:
  base-url: http://82.156.49.70
  course-url: http://82.156.49.70/new-course-table
  admin:
    sid: 2023015529
    password: Wangxin050329.
