spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hsxf?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wx050329
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.hxs.mapper: debug
    com.hxs.client: debug

wechat:
  app-id: wxd34a68970fa51736
  app-secret: 38e9f75173875c244ad08c966afccdc5
